### ISSUE TITLE
Question about file copyright

### ISSUE THREAD

**Issue by totalgee** [cinder/Cinder-VR#11]
Hi, sorry for the noise, but just wondering why all the Cinder-VR source and header files have the following first comment line:

```
Copyright 2016 Google Inc.
```

(this is before the expected Cinder Project copyright line and the license)

It's not a big deal, since the license is permissive anyhow, but just wondering if this is a cut&paste mistake (presumably not).  If not, I'd be curious to know what part of (for example) [this code](https://github.com/cinder/Cinder-VR/blob/master/include/cinder/vr/Vr.h) Google contributed! (-;

**Comment by chaoticbob** [comment]
Hi totalgee,

I am employed by Google. Per corporate policy, any code contributed to an open source project must contain the the necessary copyright information.

Hai

**Comment by totalgee** [comment]
Ah, somehow I hadn't considered that possibility. Thanks for the answer.
