### ISSUE TITLE
Access to the origin matrix (or at least the origin position).

### ISSUE THREAD

**Issue by simongeilfus** [cinder/Cinder-VR#4]
I think it would be good to expose in some way the origin transform. 

Mostly because things like `Hmd::getInputRay` relies on it to calculate results. If we translate the whole scene while leaving the origin matrix intact, the ray returned by `Hmd::getInputRay` won't be good anymore. 

Obviously you can correct the ray by transforming it to the translated space, but it would be easier to modify the origin matrix directly.

I believe the now deprecated `setLookAt` was used for that; Would be great to have it back or have at least something like this : 

``` c++
class Hmd {
public:
    void setOriginPosition( const ci::vec3 &position )
    {
        mOriginPosition = position;

        ci::vec3 mW = -normalize( mOriginViewDirection );
        ci::vec3 mU = ci::rotate( mOriginOrientation, ci::vec3( 1, 0, 0 ) );
        ci::vec3 mV = ci::rotate( mOriginOrientation, ci::vec3( 0, 1, 0 ) );    
        ci::vec3 d  = ci::vec3( - dot( mOriginPosition, mU ), - dot( mOriginPosition, mV ), - dot( mOriginPosition, mW ) );

        mat4 &m = mOriginMatrix;
        m[0][0] = mU.x; m[1][0] = mU.y; m[2][0] = mU.z; m[3][0] =  d.x;
        m[0][1] = mV.x; m[1][1] = mV.y; m[2][1] = mV.z; m[3][1] =  d.y;
        m[0][2] = mW.x; m[1][2] = mW.y; m[2][2] = mW.z; m[3][2] =  d.z;
        m[0][3] = 0.0f; m[1][3] = 0.0f; m[2][3] = 0.0f; m[3][3] = 1.0f;
    }
}
```

Is there any reason to not have `setOriginPosition` / `setLookAt` method?

EDIT: I understand that we don't want to put too much features in the Hmd class, but in my opinion if we have convenience methods like `const ci::Ray& getInputRay() const` we should also have what I'm suggesting here.
EDIT2: There's a commit waiting to be transformed into a PR here: https://github.com/simongeilfus/Cinder-VR/commit/d1fa2614bd333bfefc1fd46ee548ead8fdd5478a

**Comment by chaoticbob** [comment]
I spent sometime thinking about this. I don't think modifying the origin matrix is the right move - up for discussing it of course.

The intent of the origin matrix is to readjust the origin point from the tracking system coordinates into a more appropriate place. Moving the origin around will mess up the rendering. I could be wrong, but I think at first it sounds logical to want to move the origin point around relative to where you are - but the potential net result is confusion where (0, 0, 0) actually is.

The other thing that needs to be considered is how to handle the look direction when you move the HMD's position in world space. It can be disorienting if you use setLookAt and the user is looking up after the position change but they were looking forward before.

Suggestion:
1. Keep the origin matrix as is. It's possible to recenter this if desired, maybe allow change of offset.
2. Add a "look" matrix that gets applied before the origin matrix (over the world position) that is a one time transform to change the position and orientation of the HMD. This would be what you're modifying when you call setLookAt.
3. There probably needs to be 2 versions of setLookAt - one that preserves the current view direction, and the other lets you override it. 
4. The "look" matrix gets applied to HMD and controller input rays, so getInputRay returns the coordinates relative to where you are.

Thoughts?

**Comment by simongeilfus** [comment]
Makes sense Hai.
I didn't thought about the recentering case so it's definitely a better idea to keep things separated.

About point 3; This is probably what you meant by "2 version of setLookAt", but just in case, I'd say that `setLookAt( const ci::vec3 &position )` would be wrong as conceptually this would have nothing to do with looking at something. I would use `ci::CameraPersp` semantic instead and call it `setEyePoint`. And maybe have those 3 methods: `setLookAt( const ci::vec3 &target )`, `setLookAt( const ci::vec3 &eye, const ci::vec3 &target )` and `setEyePoint( const ci::vec3 &position )`...

**Comment by simongeilfus** [comment]
@num3ric: You definitely have more experience with this. Do you have any thoughts about this?

**Comment by chaoticbob** [comment]
Added setLookAt for position. Will add more extensive version later once I figure out how not to collapse the rotations.

https://github.com/cinder/Cinder-VR/commit/4a022debfbc4190344eab9569fcea6a40c0c9376
